# Generated by Django 6.0.1 on 2026-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vendor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
