# Generated by Django 6.0.1 on 2026-01-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
