# Generated by Django 6.0.1 on 2026-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='otp',
            new_name='otp_code',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
