# Generated by Django 6.0.1 on 2026-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_passwordresetotp_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='otp_code',
            new_name='otp',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='used',
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
