# Generated by Django 6.0.1 on 2026-01-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_otp_code_passwordresetotp_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='otp',
            new_name='otp_code',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
