# Generated by Django 6.0.1 on 2026-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_otp_passwordresetotp_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
