# Generated by Django 6.0.1 on 2026-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_early_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
