# Generated by Django 6.0.1 on 2026-01-30 08:38

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
