# Generated by Django 6.0.1 on 2026-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_blog_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
